trigger:
- main

pool:
  name: 'SelfHosted'  # Or your custom agent pool

steps:
- task: CmdLine@2
  inputs:
    script: 'java -version'


- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    
    
- script: |
    echo "Running tests in headless mode"
    mvn test -Dheadless=true
  displayName: 'Run tests'