trigger:
- main

pool:
  name: 'SelfHosted'  # Or your custom agent pool

steps:
# Install JDK 11 using Java Tool Installer
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'          # Specify JDK 11
    jdkArchitectureOption: 'x64'     # Architecture: 64-bit
    jdkSourceOption: 'LocalDirectory'

# Print the Java version to verify the installation
- task: CmdLine@2
  inputs:
    script: 'java -version'

# Maven task to build the project
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'  # Use JDK Version installed by JavaToolInstaller
    jdkVersionOption: '1.11'     # Specify JDK 11
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
